name: Java with Marven Continuos Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
  uses: docker/login-action@v3.3.0
  with:
    username: ${{ secrets.USED_USERNAME}}
    password: ${{ secrets.USED_PASSWORD}}
    
- name: Set up JDK 18
  uses: actions/setup-java@v4
  with:
      java-version: '18'
      distribution: 'adopt' 
      cache: maven
- name: Build with Maven
- working-directory: ./arquitect/home
- run: mvn clean package

- name: Build Docker Compose
- working-directory: ./home
- run: docker compose build

- name: Build to Docker Hub Registry
- run: docker tag ${{ secrets.USED_USERNAME}}/project_people:latest ${{ secrets.USED_NAME}}/project_people:${{github.run_id}}
       docker push ${{ secrets.USED_USERNAME}}/project_people:${{github.run_id}}
       docker push ${{ secrets.USED_USERNAME}}/project_people:latest

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
